version: '3.1'

services: 
  nginx:
    image: nginx:1.20.0-alpine
    container_name: dmoneyui
    volumes: 
      - ./default.conf:/etc/nginx/conf.d/default.conf 
      - ./app:/usr/share/nginx/html
    ports:
     - 8021:80